// Cart Types
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

// Orders Types
export const GET_ALL_ORDERS_USER_REQUEST = "GET_ALL_ORDERS_USER_REQUEST";
export const GET_ALL_ORDERS_USER_SUCCESS = "GET_ALL_ORDERS_USER_SUCCESS";
export const GET_ALL_ORDERS_USER_FAILED = "GET_ALL_ORDERS_USER_FAILED";

export const GET_ALL_ORDERS_SHOP_REQUEST = "GET_ALL_ORDERS_SHOP_REQUEST";
export const GET_ALL_ORDERS_SHOP_SUCCESS = "GET_ALL_ORDERS_SHOP_SUCCESS";
export const GET_ALL_ORDERS_SHOP_FAILED = "GET_ALL_ORDERS_SHOP_FAILED";

// Product Types
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
// export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_ALL_PRODUCTS_SHOP_REQUEST = "GET_ALL_PRODUCTS_SHOP_REQUEST";
export const GET_ALL_PRODUCTS_SHOP_SUCCESS = "GET_ALL_PRODUCTS_SHOP_SUCCESS";
export const GET_ALL_PRODUCTS_SHOP_FAILED = "GET_ALL_PRODUCTS_SHOP_FAILED";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

// Seller
// export const LOAD_SELLER_REQUEST = "LOAD_SELLER_REQUEST";
// export const LOAD_SELLER_SUCCESS = "LOAD_SELLER_SUCCESS";
// export const LOAD_SELLER_FAIL = "LOAD_SELLER_FAIL";

// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";
// export const UPDATE_USER_INFO_REQUEST = "UPDATE_USER_INFO_REQUEST";
// export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
// export const UPDATE_USER_INFO_FAILED = "UPDATE_USER_INFO_FAILED";

// Whishlist
export const ADD_TO_WHISHLIST = "ADD_TO_WHISHLIST";
export const REMOVE_FROM_WHISHLIST = "REMOVE_FROM_WHISHLIST";

// Initial UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_LOGIN_MODAL = "SET_LOGIN_MODAL";
export const UNSET_LOGIN_MODAL = "UNSET_LOGIN_MODAL";
export const SET_SUCCESS = "SET_SUCCESS";
export const UNSET_SUCCESS = "UNSET_SUCCESS";

// Vendor
export const LOADING_VENDOR = "LOADING_VENDOR";
export const STOP_LOADING_VENDOR = "STOP_LOADING_VENDOR";
export const SET_VENDOR = "SET_VENDOR";
export const UNSET_VENDOR = "UNSET_VENDOR";

// DATA
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
// export const SET_CATEGORIES = "SET_CATEGORIES";
// export const UNSET_CATEGORIES = "UNSET_CATEGORIES";
// export const SET_PRODUCTS = "SET_PRODUCTS";
// export const UNSET_PRODUCTS = "UNSET_PRODUCTS";
export const SET_DATA = "SET_DATA";
export const UNSET_DATA = "UNSET_DATA";
